---
name: "Tools - Validate YAML Schema"

"on":
  pull_request:
    branches:
      - "master"
    paths:
      - ".yamllint"
      - "**.yaml"
      - "**.yml"

permissions:
  contents: read

jobs:
  validate-yaml:
    name: YAML Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5.0.1

      - name: Validate YAML files
        run: yamllint .
